#!/usr/bin/env ruby
[1,2,3,4,5,6,7,8,9].each do |number|

end
(1..9).each {| number | number }

[1,2,3,4].each_with_index do | number, pos |
  puts "numero: #{number} => posicion: #{pos}"
end

impares = [1,2,3,4,5,6,7].select {|number| number%2 != 0}
puts impares
